---
apiVersion: v1
kind: Namespace
metadata:
  name: apps

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: private-appv2
  namespace: apps
data:
  api.json: |
    {
      "forecast": [
        { "id": 1, "city": "GopherCity", "weather": "Cloudy", "dt": "3128231402" },
        { "id": 2, "city": "City of Gopher", "weather": "Rainy", "dt": "3128231402" },
        { "id": 3, "code": "GopherCentral", "weather": "Shiny", "dt": "3128231402" }
      ],
      "forecast-fr": [
        { "id": 1, "city": "GopherCity", "weather": "Nuageux", "dt": "3128231402" },
        { "id": 2, "city": "City of Gopher", "weather": "Pluvieux", "dt": "3128231402" },
        { "id": 3, "code": "GopherCentral", "weather": "Ensoleill√©", "dt": "3128231402" }
      ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-app
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-appv2
  template:
    metadata:
      labels:
        app: private-appv2
    spec:
      containers:
        - name: api
          image: ghcr.io/traefik-workshops/api-server:v0.1.0
          args: ["-data", "/api/api.json", "-openapi", "/public/openapi.yaml", "-errorrate", "2"]
          imagePullPolicy: Always
          volumeMounts:
          - name: api-data
            mountPath: /api
          - name: openapi
            mountPath: /public
      volumes:
        - name: api-data
          configMap:
            name: private-appv2-data
        - name: openapi
          configMap:
            name: private-appv2-openapispec

---
apiVersion: v1
kind: Service
metadata:
  name: private-appv2
  namespace: apps
  labels:
    app: private-appv2
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: api
  selector:
    app: private-appv2

